// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXErXq3xSTbu1wsMNB56YEAlIigNTykA',
    appId: '1:98563951210:web:43e143584d96612aff1813',
    messagingSenderId: '98563951210',
    projectId: 'reddit-375e3',
    authDomain: 'reddit-375e3.firebaseapp.com',
    storageBucket: 'reddit-375e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdJtMWtLRMxci1dKpJZ_8S93yjzVosdY',
    appId: '1:98563951210:android:f031ee044c58417dff1813',
    messagingSenderId: '98563951210',
    projectId: 'reddit-375e3',
    storageBucket: 'reddit-375e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrFSBstWUtuHtB8T3q9vsZST65pXOH0g',
    appId: '1:98563951210:ios:c358c36b36bef28cff1813',
    messagingSenderId: '98563951210',
    projectId: 'reddit-375e3',
    storageBucket: 'reddit-375e3.firebasestorage.app',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQrFSBstWUtuHtB8T3q9vsZST65pXOH0g',
    appId: '1:98563951210:ios:c358c36b36bef28cff1813',
    messagingSenderId: '98563951210',
    projectId: 'reddit-375e3',
    storageBucket: 'reddit-375e3.firebasestorage.app',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgXErXq3xSTbu1wsMNB56YEAlIigNTykA',
    appId: '1:98563951210:web:3f4a9a858022e2e5ff1813',
    messagingSenderId: '98563951210',
    projectId: 'reddit-375e3',
    authDomain: 'reddit-375e3.firebaseapp.com',
    storageBucket: 'reddit-375e3.firebasestorage.app',
  );
}
