// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9obJjVW9H3bz3UL0IzphT9vWGYQJh7ZE',
    appId: '1:568003608686:web:26b0ad867e30163356e67f',
    messagingSenderId: '568003608686',
    projectId: 'reddit-9a073',
    authDomain: 'reddit-9a073.firebaseapp.com',
    storageBucket: 'reddit-9a073.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJqMwmo0nKGntTfp0tpkW4QN83z-9X7tM',
    appId: '1:568003608686:android:92af3b5ebc02ecbd56e67f',
    messagingSenderId: '568003608686',
    projectId: 'reddit-9a073',
    storageBucket: 'reddit-9a073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7M82BY_N8nnfaFb5P3-OXjlp5g4ziDAk',
    appId: '1:568003608686:ios:3ab06edda040da2856e67f',
    messagingSenderId: '568003608686',
    projectId: 'reddit-9a073',
    storageBucket: 'reddit-9a073.firebasestorage.app',
    iosBundleId: 'com.example.redditApp',
  );
}
